# Generated by Django 4.2.16 on 2026-03-27 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='target_admin',
            field=models.ForeignKey(blank=True, help_text='Admin partenaire cible de la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
