# Generated by Django 4.2.16 on 2026-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.IntegerField(unique=True)),
                ('block_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('document_unique_number', models.CharField(max_length=30)),
                ('document_hash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('timestamp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blockchain_records',
                'ordering': ['block_index'],
            },
        ),
    ]
